### ISSUE TITLE
Question about add/edit product page - "next combination" link

### ISSUE THREAD

**Issue by matks** [PrestaShop/prestashop-specs#106]
@marionf I think I found a missing item 😄it was well hidden

Meet the "next combination" link
<img width="1206" alt="Capture d’écran 2020-03-16 à 18 01 03" src="https://user-images.githubusercontent.com/3830050/76782229-405d9000-67b0-11ea-9803-84b95e83331e.png">
See at the top right

And if you click on it, you can navigate in **the combinations of the product** (and now you have a "previous combination" link too)

The issue ... what is the expected behavior if I
- open 1st combination
- modify settings
- then go to next combination WITHOUT HITTING SAVE
- modify settings of combination number two
- go to next combination, again without hitting save

Should we autosave modifications when switching tab ?

If we dont, user might modify, let's say, 10 combinations then hit "save". So we submit 10 combinations form at once. What happens if there is errors on one ? On two ?

So I suggest we autosave this 😬

**Comment by marionf** [comment]
@matks 

Yeah, nice catch, you are right I missed it :+1: 

> user might modify, let's say, 10 combinations then hit "save". So we submit 10 combinations form at once.

It seems to work like that actually, but you are right that isn't the best behavior if there are errors

I am ok with the autosave, each time the user click on next or previous combination button
I add this in the specs: https://github.com/PrestaShop/prestashop-specs/commit/60eed17b771a059ef90dacb7bdd87f7f7362ff79

**Comment by matks** [comment]
> If we dont, user might modify, let's say, 10 combinations then hit "save". So we submit 10 combinations form at once. What happens if there is errors on one ? On two ?

Now I see that this question applies also to tabs. If I fill my "Shipping" tab with data, then my "SEO" tab with data and I hit "save" button, what happens if I have errors on both tabs ? I can only display the errors on the tab the user sees.

**Comment by marionf** [comment]
@matks You can see in the video below the actual behavior:
https://drive.google.com/file/d/1VdP1NzghtbCaGqT63wpF6lqtNnaGSsKk/view?usp=sharing

But it's not really the best behavior.
Is it possible to autosave when the user change tab ?

**Comment by matks** [comment]
> Is it possible to autosave when the user change tab ?

Yes and it looks like the best solution to avoid the issue above.
You'll need to tell us how it behaves.

For example there can be multiple different behaviors:

1) No autosave, prevent user from leaving
When we detect a click on another tab, we dont open the new tab and display a warning message to user: "Warning ! You have unsaved settings on this tab"

2) Silent autosave
When we detect a click on another tab, we trigger the save. if it works, we open the new tab and display a success message. If it fails, we display a warning message to user: "Warning ! Cannot save this tab it has issues"

This one is the best UI as, as long as user provides right values, user does not see any transition or blocking item.

3) Ask confirmation first autosave
When we detect a click on another tab, we display a modal "hi ! you have unsaved changes in this tab, do you wish to discard them or do you wish to save them" and let user choose.

**Comment by marionf** [comment]
Yeah, option 2 sounds better
Specs updated here: https://github.com/PrestaShop/prestashop-specs/commit/7e48ce1ab6a57e8043aa41321af87eabcd3b172c

**Comment by matks** [comment]
@marionf After discussing this with @PrestaShop/prestashop-core-developers a lot of people are very worried about the impact on the user experience of an autosave 😅they wanted to double-check, with @TristanLDD too maybe, that this rule for tabs is wished

**Comment by marionf** [comment]
All right, I ping also @MatShir as it's about the product page

**Comment by MatShir** [comment]
The combination edition will be managed in pop in and it won't have anymore a link to navigate through between the differents product combinations pages. The pop-in will create a context to save the combination information (https://invis.io/3RWZILBJWQH#/414747859_Edit_Comb-_Modale_Top).

**Comment by vincentbz** [comment]
Hi guys,
As I was looking for the next improvements for the product page, I've found that topic.
I'm a former Prestashop PM and now a web merchant on a prestashop shop.
I'm dealing with around 50 products but each product has between 9 and 48 combinations. Emerchants never modify only one combination. We always modify X combinations in X products. For example today I had to modify 6 combinations on each product. 3 days ago, it was 3. Next week i'll have to modify others.
If you remove these buttons, you multiply by two the number of clicks for each combination. 6x50=300, you add 300 clicks (600 if you add the save button on each combination modification).
Another case, very frequent. When I create a new product, I have to verify each combination one by one to avoid mistakes. It means that for every combination i'll have to open, scroll down to verify, close, open the next one... X number of combinations. CUrrently it's : verification + next button. That's all
From a merchant point of view, this is a functional regression and it will be painfull. Because we always deal with a lot of combinations. It's never one combination today, the next one tomorrow. 
I hope you'll find a better solution :)
And if you need to talk about it, don't hesitate :)

Thanks ! (and hello to the team)
